### ISSUE TITLE
pipe output

### ISSUE THREAD

**Issue by lixee** [kevineye/docker-shairport-sync#3]
I'm new to docker and need some help.

mkfifo /some/pipe
docker run -d \
    --name shairport-pipe \
    --net host \
    --device /dev/snd \
    -e AIRPLAY_NAME=Docker \
    -v /some/pipe:/output \
    kevineye/shairport-sync \
        -o pipe \
        -- /output"

So everything is clear except for the last two lines. I created a pipe, I gave the docker an custom AIRPLAY_NAME, I configured the output directory, but what exactly do I have to do regarding "-o pipe" and "-- /output"?

**Comment by lixee** [comment]
Got it myself ;)

**Comment by melyux** [comment]
How did you figure it out? This project seems dead.
