### ISSUE TITLE
 ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave

### ISSUE THREAD

**Issue by sebastian-ruiz** [kevineye/docker-shairport-sync#5]
I run:

```
docker run -d \
    --net host \
    --device /dev/snd \
    -e AIRPLAY_NAME=Docker \
    kevineye/shairport-sync
```

and I get this error in the logs whenever I try and play music:

` ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave`

I tried to google the issue but no working solution. Any help would be great!

**Comment by sebastian-ruiz** [comment]
Solved using http://forums.debian.net/viewtopic.php?t=123902

1. Create a file called `/etc/modprobe.d/default.conf` with this content:

```
options snd_hda_intel index=1
```

2. Reboot

**Comment by kreacjusz** [comment]
Thanks it works on HP Thin client t630, OMV OwnTone.
and doing this:
https://forum.openmediavault.org/index.php?thread/48656-owntone-computer-sound-alsa-missing/
